export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const SET_SELECTED_PRODUCT_QUANTITY = 'SET_SELECTED_PRODUCT_QUANTITY';
export const CLEAN_SELECTED_PRODUCT = 'CLEAN_SELECTED_PRODUCT';
